# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Bulid serverless

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  AWS_REGION: ca-central-1                   # set this to your preferred AWS region, e.g. us-west-1

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pre-commit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint using  with pre commit
      run: |
        pre-commit run --all-files --verbose


  deploy-dev:

      runs-on: ubuntu-latest
      environment: 'DEV'
      needs: build
      steps:
      - uses: actions/checkout@v3
      - name: Dev Bulid code
        run: |
          sh +x bulid.sh

  deploy-prod:

      runs-on: ubuntu-latest
      environment: 'PROD'
      needs: [ build,deploy-dev]
      steps:
      - uses: actions/checkout@v3
      - name: Prod Bulid code
        run: |
          sh +x bulid.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: lambda_profile

      - name: Copy the Zip file to AWS S3
        run: |
          echo `pwd`
          echo `ls`
          echo `ls build_code`
          aws s3 cp lambda_zip/github_archive.zip s3://hari-redshift123/code/lambda/zip/
          
      - name: Delete the existing files in S3
        run: |
          aws s3 rm s3://hari-redshift123/github/download/ --recursive
          
      
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
                --function-name  github_archive \
                --s3-bucket hari-redshift123 \
                --s3-key code/lambda/zip/github_archive.zip
      
